# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sam's Skunkpit
tagline:          No games no life
url:              http://gamesketches.gitpages.io
paginate:         1
baseurl:          /
author:
  name:           Sam Von Ehren
  url:            https://twitter.com/samvonehren
  email:          sam.von.ehren@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/gamesketches/
